# importing the python img which imports the os automatically
FROM python:3.13.3
WORKDIR /app
COPY api.py /app
COPY ml_layer.py /app
COPY requirements.txt /app
RUN pip3 install -r requirements.txt
EXPOSE 7860
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "7860"]