# importing the python img which imports the os automatically
FROM python:3.13.3
WORKDIR /app
COPY frontend.py /app
COPY requirements.txt /app
RUN pip3 install -r requirements.txt
EXPOSE 3000
CMD ["python3", "frontend.py"]