# importing the python img which imports the os automatically
FROM python:3.13.3
WORKDIR /app
COPY frontend.py /app
COPY frontend_requirements.txt /app

# to not ensure stale view 
RUN apt-get update 

#for health check ups in docker compose
RUN apt-get --yes install curl

RUN pip3 install -r frontend_requirements.txt
EXPOSE 80
EXPOSE 443
CMD ["python3", "frontend.py"]